Fixed Scaling issues for the dock when previewing on different scales
pop-os/cosmic-dock pull request #171
Opened 2022-10-03 21:09 UTC by NathanaelA

This fixed #44, a rebase of my #48 on to Jammy (with some new fixes).    This also has code to fix the potential error that was reported in #148 where apparently the the `scale` must be invalid directly after a monitor is plugged in/unplugged.  

In addition the original math for the windowPreview was subtracting -22 pixels AFTER the scale calculation, this 22 pixels  (11 for each side) should have been subtracted out before the `scale` was applied so that this window (see below) is actually centered properly on scaled displays.

![image](https://user-images.githubusercontent.com/850871/193682737-2d68fabe-dea6-42bb-b99f-a608b6e98149.png)

2022-10-03 22:15 UTC, n3m0-22 requested changes
The [issue](https://github.com/pop-os/cosmic-dock/pull/148#pullrequestreview-979353396) I mention in the previous PR has been resolved. This is testing well on lo-dpi and hi-dpi displays, but I am still seeing the off center issue. In the screenshot below using the active hint on the window edge as a guide you can see it is shifted further to the right. This happens on all displays (both single and multiple), screen resolutions, and dock configurations I have tested.

![dock-center](https://user-images.githubusercontent.com/11048214/193694794-b90e773d-8602-4ef7-b020-01accba4e593.png)

2022-10-03 23:33 UTC, NathanaelA commented
1. Without the patch, does it center properly?    

2. Is this only LDPI?   I'm using a Bonobo like this:
 ![image](https://user-images.githubusercontent.com/850871/193703605-36aa5890-1c70-44ab-aeac-8faf58d1ef07.png)
And it looks correct.   (afaik, with the daemon disabled the bottom setting doesn't do anything, but the daemon caused lots of weird issues in day to day work, that I finally disabled it).

However, I did notice that if I switched it down to 100% scaling that it wasn't centered -- but 100% should be handled identical to the original code without any of my extra scaling handling code added -- because that would be ( Width / 1 = Width ).

2022-10-04 14:04 UTC, n3m0-22 approved these changes
After checking all scaling levels on a few more displays I am seeing the centering issue is only at 100% scaling and is present prior to this PR so it is not a regression. I see no other reason not to approve this.

2022-10-04 17:17 UTC, 13r0ck approved these changes
Thank you. Sorry this dragged on waaaaaay longer than it should have. I really appreciate your help and persistence.

2022-10-04 17:18 UTC, merged