feat(css): styling for dock on impish
pop-os/cosmic-dock pull request #65
Opened 2021-09-30 20:29 UTC by isantop

Upgrading to the new version of Cosmic Dock (based on GNOME 40-compatible DtD) introduced styling issues that needed to be fixed. This replaces the styling with an updated stylesheet that better supports the new version of the dock. 

This new styling also allows hovering and clicking on items with the mouse cursor against the edge of the screen. This results in usability improvements because the mouse only needs to aim in one direction, without needing to aim across the dock.

2021-09-30 21:49 UTC, jackpot51 approved these changes

2021-10-01 18:34 UTC, leviport requested changes
If I disable "Extend dock to edges of screen", the highlight shadow thingy around hovered or active window icons spills off the edge of the dock. 

![Screenshot from 2021-10-01 12-30-16](https://user-images.githubusercontent.com/13512097/135669816-af9fc7f2-990b-47ab-beb9-a7c9a9d8abab.png)

2021-10-01 21:46 UTC, isantop commented
The latest commits have corrected the overhang issue and added back styling for the notification badges, which were removed in the last commit.

2021-10-04 21:56 UTC, leviport approved these changes
The icon highlights no longer extends past the edge when the dock is in floating mode, and the notification counters are now styled correctly.

The icon highlights no longer touch the edges of the dock in non-floating mode, but I think this looks fine:
![Screenshot from 2021-10-04 15-51-42](https://user-images.githubusercontent.com/13512097/135929957-2bf019d9-c429-4cd3-aac0-f9ba52936ed1.png)

2021-10-05 13:31 UTC, merged